[package]
name = "solagent"
version = "0.1.1"
edition = "2021"
authors = ["zTgx <beautifularea@gmail.com>"]
repository = "https://github.com/zTgx/solagent.rs.git"
readme = "README.md"
keywords = ["solana", "ai", "agent"]
license = "MIT"
description = "connect any Ai agents to solana protocols in Rust."

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.42.0", features = ["full"] }
serde_json = "1.0"
actix-web = "4"
colored = "2.0"
lazy_static = "1.5.0"
toml = "0.8.19"
rig-core = "0.6.0"
clap = { version = "4.5.23", features = ["derive"] }
thiserror = "2.0.9"
anyhow = "1.0.95"
chrono = { version = "0.4.39", features = ["serde"] } 
reqwest = { version = "0.12", features = ["blocking", "json"] }
async-trait = "0.1.83"
uuid = { version = "1.11.0", features = ["v4"] }
