[package]
name = "solagent"
version = "0.1.5"
edition = "2021"
authors = ["zTgx <beautifularea@gmail.com>"]
repository = "https://github.com/zTgx/solagent.rs.git"
readme = "README.md"
keywords = ["solana", "ai", "agent"]
license = "MIT"
description = "connect any ai agents to solana protocols in Rust."

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.5.0"
rig-core = "0.6.0"
async-trait = "0.1.83"
solana-client = "2.1.7"
solana-sdk = "2.1.7"
mpl-token-metadata = { version = "5.1.0", features = ["serde"] }
spl-token = "7.0.0"
spl-associated-token-account = "6.0.0"
solana-program = "2.1.7"
thiserror = "2.0.9"
reqwest = { version = "0.12", features = ["json", "multipart"] }
bincode = "1.3.3"
base64 = "0.22.1"
anyhow = "1.0.80"

[dev-dependencies]
tokio = { version = "1.42.0", features = ["full"] }
rig-core = "0.6.0"

#################################################################
# # EXAMPLE: BASIC
#################################################################
[[example]]
name = "deploy_collection"
path = "examples/basic/deploy_collection.rs"

[[example]]
name = "deploy_token"
path = "examples/basic/deploy_token.rs"

[[example]]
name = "get_balance"
path = "examples/basic/get_balance.rs"

[[example]]
name = "mint_nft_to_collection"
path = "examples/basic/mint_nft_to_collection.rs"

[[example]]
name = "create_gibwork_task"
path = "examples/basic/create_gibwork_task.rs"

#################################################################
# # EXAMPLE: DeFi
#################################################################
[[example]]
name = "jupiter_stake"
path = "examples/defi/jupiter_stake_sol.rs"

[[example]]
name = "jupiter_swap"
path = "examples/defi/jupiter_swap.rs"

[[example]]
name = "pumpfun_launch_token"
path = "examples/defi/pumpfun_launch_token.rs"

#################################################################
# # EXAMPLE: RIG
#################################################################
[[example]]
name = "create_solana_tools"
path = "examples/rig/create_solana_tools.rs"

[[example]]
name = "dynamic_tools"
path = "examples/rig/dynamic_tools.rs"

[[example]]
name = "running_locally"
path = "examples/rig/running_locally.rs"

#################################################################
# # EXAMPLE: UTILS
#################################################################
[[example]]
name = "jupiter_fetch_price"
path = "examples/utils/jupiter_fetch_price.rs"

[[example]]
name = "pyth_fetch_price"
path = "examples/utils/pyth_fetch_price.rs"
