[package]
name = "solagent-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[[example]]
name = "solagent"
path = "../examples/solagent.rs"

[dependencies]
